
version: "3.9"
services:
  exporter:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
      - ./reports:/app/reports
    command: bash -lc "pip install -q -r requirements.txt && python alerts/prometheus_exporter.py"
    ports: ["9100:9100"]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]
    depends_on: [exporter]

  grafana:
    image: grafana/grafana
    environment: [GF_SECURITY_ADMIN_PASSWORD=admin]
    ports: ["3000:3000"]
    depends_on: [prometheus]
